### PR TITLE
translation: Fix typo on Chinese Simplified

### PR DESCRIPTION
**Pull request by yangyangdaji**
Log: Fix typo `PullRequest`→ `Pull Request ` on
Chinese Simplified

Split from #35

Signed-off-by: yangyangdaji <1504305527@qq.com>

### CODE REVIEW

**Comment by yangyangdaji** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by yangyangdaji** [comment]
@justforlxz

https://github.com/linuxdeepin/deepin-tweak/pull/35 
已经打开好久了  一直没动静 我想着把它拆分出来 方便你们审查

**Comment by yangyangdaji** [comment]
我可能描述有点问题 等一下

**Comment by yangyangdaji** [comment]
现在可以了

**Review by BLumia — APPROVED** [review]

**Pull request merged**
